name: Conditional examples

on:
  workflow_dispatch:
    inputs:
      fail_my_step:
        description: 'Shall we fail the step? (yes/no)'
        required: true
        type: string
        default: 'yes'
jobs:
  the-best-job:
    runs-on: ubuntu-latest
    steps:
      - name: yes was passed in as 'fail_my_step'
        if: inputs.fail_my_step == 'yes'
        run: echo "you said yes!! :)"

      - name: no was passed in as 'fail_my_step'
        run: echo "you said no !! :("
        if: inputs.fail_my_step == 'no'

      - name: Step that may fail
        shell: bash
        run: |
          echo "Hello, I may fail"
          if [ "yes" = "${{ inputs.fail_my_step }}" ]; then
            exit 42
          fi

      - name: Another step
        run: echo "another step..."
          
      - name: Another step
        run: echo "another step..."
          
      - name: Step that runs on failure
        if: failure()
        run: echo "Oh no... call for help!"

      - name: Step that always runs
        if: always()
        run: echo "I will always run!"



        
