name: My first workflow

on: push

jobs:
  my-amazing-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The amazing job has started"
      - run: echo "This was triggered by a ${{ github.event_name }} event."
      - run: echo "The amazing job is complete"
  my-amazing-checkout-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Cloning ${{ github.repository }} to the runner..."
      - name: Checkout repo
        uses: actions/checkout@v4.1.1
      - run: echo "The repo has been cloned and is ready for... well... anything!"
      - name: List files in repo
        run: |
          ls -lah ${{ github.workspace }};
          echo "Contents of README.md";
          cat README.md
      - run: echo "This job's status is ${{ job.status }}"
        
  build-and-test:
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v4.1.1
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3.2.0
      with:         
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./TestabilityDemo.Tests/TestabilityDemo.Tests.csproj
          
    - name: Build
      run: dotnet build ./TestabilityDemo.Tests/TestabilityDemo.Tests.csproj --no-restore

    - name: Test
      run: dotnet test ./TestabilityDemo.Tests/TestabilityDemo.Tests.csproj --no-build --logger "html" --results-directory "test_results"

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: code/test_results
